---
title: "ch3_data_handling"
output: html_document
date: "2023-02-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)


```

## Tidyverse 

```{r, eval=F}
dat <- read_csv("Example_data/Ch3_chb.csv") 
dat1 <- dat #원본 보존
```

```{r}
dat1 %>% 
  select(id, b_alt, b_bil, b_alb) %>% 
  print(n=4)

dat1 %>% 
  select(-id, -index_date) %>% 
  colnames()

dat1 %>% 
  select(b_alt, m6_alt, m12_alt) %>% 
  print(n=4)

dat1 %>% 
  select(contains('m6')) %>% 
  print(n=4)

dat1 %>% 
  rename(sex=gender) %>% 
  print(n=4)
```

```{r}
dat1 %>% 
  mutate(age_gr=ifelse(age>=50, 'above_50', 'below_50')) %>% 
  count(age_gr)
```

```{r}
dat1 %>% 
  mutate(bil_gr=ifelse(b_bil>=3, 'C', 
                       ifelse(b_bil>=2, 'B', 'A'))) %>% 
  select(id, b_bil, bil_gr) %>% 
  print(n=20) %>% 
  count(bil_gr)
```

```{r}
dat1 %>% 
  mutate(risk_gr=ifelse(age>=50 & lc==1, 'high_risk',
                        ifelse(age<50 & lc==0,'low_risk', 'intermediate_risk'))) %>% 
  count(risk_gr)
```



